import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./global.css";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "700"], // Define los pesos que necesitas
});

const geistSans = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "700"], // Define los pesos que necesitas
  variable: "--geist-sans-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}